version: "3.8"

services:
  venom-wa-api:
    build:
      context: .
    container_name: venom-wa
    ports:
      - "3000:3000"
    volumes:
      # 1. Map kode sumber dari host ke container (Bind Mount)
      - /home/admin01/venom-wa:/app

      # 2. "Trik" untuk node_modules:
      # Mencegah node_modules dari host menimpa yang ada di container.
      # Ini menggunakan node_modules yang diinstal oleh Dockerfile.
      - /app/node_modules

      # 3. Tetap gunakan Docker Volume untuk data sesi yang persisten
      - venom_sessions:/app/tokens

    # 4. Ganti perintah startup untuk menggunakan nodemon
    command: npm run dev

    networks:
      - mysql_default
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    env_file:
      - .env

networks:
  mysql_default:
    external: true

volumes:
  venom_sessions: # Kita tidak lagi butuh volume untuk node_modules karena sudah ditangani di atas
